"""add optuna_studies table

Revision ID: 1c032198859a
Revises: 68fa695ae236
Create Date: 2026-03-22 18:49:41.916903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c032198859a'
down_revision: Union[str, Sequence[str], None] = '68fa695ae236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optuna_studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.String(length=100), nullable=False),
    sa.Column('study_name', sa.String(length=200), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('n_completed', sa.Integer(), nullable=False),
    sa.Column('n_pruned', sa.Integer(), nullable=False),
    sa.Column('best_mean_reward', sa.Float(), nullable=True),
    sa.Column('best_hyperparameters', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optuna_studies')
    # ### end Alembic commands ###
