"""add model_registry table

Revision ID: 3d42eab7a58e
Revises: 1c032198859a
Create Date: 2026-03-22 19:32:38.557305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d42eab7a58e'
down_revision: Union[str, Sequence[str], None] = '1c032198859a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('previous_production_id', sa.Integer(), nullable=True),
    sa.Column('mean_reward', sa.Float(), nullable=True),
    sa.Column('promoted_by', sa.Integer(), nullable=True),
    sa.Column('promotion_comment', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['previous_production_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['promoted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_registry')
    # ### end Alembic commands ###
