"""add artifacts artifact_lineage and experiment tags

Revision ID: 672529a126ef
Revises: 08fb955aad2f
Create Date: 2026-03-23 00:26:23.364987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672529a126ef'
down_revision: Union[str, Sequence[str], None] = '08fb955aad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_lineage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_experiment_id', sa.Integer(), nullable=True),
    sa.Column('child_experiment_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['parent_experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('experiments', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('experiments', sa.Column('parent_experiment_id', sa.Integer(), nullable=True))
    # FK constraint on parent_experiment_id enforced at ORM level; SQLite does not support ALTER ADD FK
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'parent_experiment_id')
    op.drop_column('experiments', 'tags')
    op.drop_table('artifacts')
    op.drop_table('artifact_lineage')
    # ### end Alembic commands ###
