"""add custom_environments table

Revision ID: e7b6c9334276
Revises: e48a93340b79
Create Date: 2026-03-18 12:26:35.548425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b6c9334276'
down_revision: Union[str, Sequence[str], None] = 'e48a93340b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('entry_point', sa.String(length=255), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('observation_space_spec', sa.JSON(), nullable=True),
    sa.Column('action_space_spec', sa.JSON(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('experiments', sa.Column('mean_reward', sa.Float(), nullable=True))
    op.add_column('experiments', sa.Column('std_reward', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'std_reward')
    op.drop_column('experiments', 'mean_reward')
    op.drop_table('custom_environments')
    # ### end Alembic commands ###
