# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"j\n\x0ePredictRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\x05\x12\x13\n\x0bobservation\x18\x02 \x03(\x02\x12\x15\n\rdeterministic\x18\x03 \x01(\x08\x12\x15\n\rmodel_version\x18\x04 \x01(\x05\"`\n\x0fPredictResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nlatency_us\x18\x03 \x01(\x03\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"Y\n\x13\x42\x61tchPredictRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\x05\x12+\n\x08requests\x18\x02 \x03(\x0b\x32\x19.inference.PredictRequest\"_\n\x14\x42\x61tchPredictResponse\x12-\n\tresponses\x18\x01 \x03(\x0b\x32\x1a.inference.PredictResponse\x12\x18\n\x10total_latency_us\x18\x02 \x01(\x03\":\n\x10ModelInfoRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\x05\"\x90\x01\n\x11ModelInfoResponse\x12\x15\n\rexperiment_id\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\talgorithm\x18\x03 \x01(\t\x12\x13\n\x0bmean_reward\x18\x04 \x01(\x02\x12\x17\n\x0ftotal_timesteps\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t2\xf0\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12O\n\x0c\x42\x61tchPredict\x12\x1e.inference.BatchPredictRequest\x1a\x1f.inference.BatchPredictResponse\x12I\n\x0cGetModelInfo\x12\x1b.inference.ModelInfoRequest\x1a\x1c.inference.ModelInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=136
  _globals['_PREDICTRESPONSE']._serialized_start=138
  _globals['_PREDICTRESPONSE']._serialized_end=234
  _globals['_BATCHPREDICTREQUEST']._serialized_start=236
  _globals['_BATCHPREDICTREQUEST']._serialized_end=325
  _globals['_BATCHPREDICTRESPONSE']._serialized_start=327
  _globals['_BATCHPREDICTRESPONSE']._serialized_end=422
  _globals['_MODELINFOREQUEST']._serialized_start=424
  _globals['_MODELINFOREQUEST']._serialized_end=482
  _globals['_MODELINFORESPONSE']._serialized_start=485
  _globals['_MODELINFORESPONSE']._serialized_end=629
  _globals['_INFERENCESERVICE']._serialized_start=632
  _globals['_INFERENCESERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
